ui: mocha-qunit
browsers:
  - name: iphone
    version: [7.1,latest]
  - name: android
    version: [4.1,latest]
  - name: ie
    version: 9..latest
  - name: safari
    version: latest
  - name: opera
    version: latest
  - name: firefox
    version: latest
  - name: chrome
    version: latest
